#!/bin/sh

MICORC=/dev/null
export MICORC

# run Server
rm -f hello.ref
./server -ORBSL3 -ORBCSIv2 -ORBSL3CmdExt -ORBSL3TCPIPAcceptor -ORBSL3CSIServerUser karel,cobalt -ORBSL3CSIServerRealm @objectsecurity.com &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0
for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r hello.ref ; then break ; else sleep 1 ; fi ; done

# run client
./client -ORBSL3 -ORBCSIv2 -ORBSL3CmdExt -ORBSL3TCPIPInitiator -ORBSL3CSIClientUser @objectsecurity.com,karel,cobalt

