#!/bin/sh

MICORC=/dev/null
export MICORC

rm -f NameService-root.inf

echo "starting Naming Service daemon ..."
nsd -ORBIIOPAddr inet:`uname -n`:12456 &
nsd_pid=$!

sleep 3

# run Server
#rm -f hello.ref
./server -ORBSL3 -ORBInitRef NameService=corbaloc::`uname -n`:12456/NameService &
server_pid=$!

trap "kill $nsd_pid $server_pid > /dev/null 2> /dev/null" 0
#for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r hello.ref ; then break ; else sleep 1 ; fi ; done

sleep 2

# run client
./client -ORBSL3 -ORBInitRef NameService=corbaloc::`uname -n`:12456/NameService
