#!/bin/sh

MICORC=/dev/null
export MICORC

# run Server
rm -f hello.ref
./server -ORBSL3 -ORBSL3CmdExt -ORBSL3TLSAcceptor2 localhost:2313 -ORBSL3TLSAcceptorOptions ca_cert.pem,s_cert.pem,s_key.pem -ORBSL3TLSAcceptorVerifyDepth 1 &
server_pid=$!

trap "kill $server_pid > /dev/null 2> /dev/null" 0
for i in 0 1 2 3 4 5 6 7 8 9 ; do if test -r hello.ref ; then break ; else sleep 1 ; fi ; done

# run client
./client -ORBSL3 -ORBSL3CmdExt -ORBSL3TLSInitiator2 localhost:7813 -ORBSL3TLSInitiatorOptions ca_cert.pem,c_cert.pem,c_key.pem -ORBSL3TLSInitiatorVerifyDepth 1

